apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: haikumanagement
  name: pod-and-pod-logs-reader
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "delete"]
